const char Index1[] =
"<!DOCTYPE html>"
"<html lang='es'>"
"<head>"
    "<meta charset='UTF-8'>"
    "<meta http-equiv='X-UA-Compatible' content='IE=edge'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<title>Naceli | Home</title>"
    "<style>"
     "body { background-color: #110d0d; font-family: Arial, Helvetica, Sans-Serif; Color: #ffffff; text-align:center; }"
    "</style>"
"</head>"
"<body>"
    "<font size='6'>Vamos a configurar tú dipositivo</font> <br>"
    "<font size='5'>Selecciona la red a la que deseas conectarlo</font> <br><br>";

const char Index2[]=
    "<form action='' method='post'><label>O hazlo de forma manual</label><input type='text' name='ssid'><input type='submit' value='Ingresar'></form>"
    "<br><br><font size '4'>Para volver a escanear redes recarga la página</font><br>"
    
"</body>"
"</html>";

const char password1[]=
"<!DOCTYPE html>"
"<html lang='es'>"
"<head>"
    "<meta charset='UTF-8'>"
    "<meta http-equiv='X-UA-Compatible' content='IE=edge'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<title>Naceli | Home</title>"
    "<style>"
     "body { background-color: #110d0d; font-family: Arial, Helvetica, Sans-Serif; Color: #ffffff; text-align:center; }"
    "</style>"
"</head>"
"<body>"
    "<font size='6'>Para la red</font> <br>"
    "<font size='5'>";

const char password2[]=
"</font> <br><br>"
    "<form id='contr' method='POST'>"
    "Contraseña: <input type='password' placeholder='Ingresa la contraseña' name='pass'>"
    "<input type='submit' value='Aceptar'>"
      "</form> "
    
"</body>"
"</html>";

const char* updatecharge =
"<!DOCTYPE HTML>"
"<html>"
 "<head>"
  "<meta content='text/html; charset=ISO-8859-1' http-equiv='content-type'>"
  "<meta name = 'viewport' content = 'width = device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable=0'>"
  "<title>Naceli | Update</title>"
  "<style>"
   "body { background-color: #110d0d; font-family: Arial, Helvetica, Sans-Serif; Color: #ffffff; text-align:center; }"
  "</style>"
 "</head>"
 "<br><br>"
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
   "<input type='file' name='update'>"
        "<input type='submit' value='Update'>"
    "</form>"
 "<div id='prg'>progress: 0%</div>"
 "<script>"
  "$('form').submit(function(e){"
  "e.preventDefault();"
  "var form = $('#upload_form')[0];"
  "var data = new FormData(form);"
  " $.ajax({"
  "url: '/update',"
  "type: 'POST',"
  "data: data,"
  "contentType: false,"
  "processData:false,"
  "xhr: function() {"
  "var xhr = new window.XMLHttpRequest();"
  "xhr.upload.addEventListener('progress', function(evt) {"
  "if (evt.lengthComputable) {"
  "var per = evt.loaded / evt.total;"
  "$('#prg').html('progress: ' + Math.round(per*100) + '%');"
  "}"
  "}, false);"
  "return xhr;"
  "},"
  "success:function(d, s) {"
  "console.log('success!')"
 "},"
 "error: function (a, b, c) {"
 "}"
 "});"
 "});"
 "</script>"
"</html>";
